### ISSUE TITLE
Game feedback

### ISSUE THREAD

**Issue by JosieAilsa** [MustafaNasirov/jump-js-game#1]
## Version Control

- Make sure you are adding and committing enough - you only have 11 commits which does not meet the brief requirements. You have meaningful messages but need to make sure you are adding and regularly - look up atomic commits. [https://www.freshconsulting.com/insights/blog/atomic-commits/](https://www.freshconsulting.com/insights/blog/atomic-commits/)

## Site Output

- This is great game Mustafa - what a turnaround from last week. I can see how much effort you have put into this well done.

## Readability

- You’ve started to add comments throughout your code to explain logic - keep this up!
- Your functions and variables are really well named.

## Responsiveness

- Its responsive across device widths, nice work!

## Code Knowledge and Use

- Reaaally nice use of a guard clauses in your functions!
- Don’t use `var`!! Let and const were given to use in ES6 for a reason (var has some bizarre scoping behaviour), so use them - there is no need to use `var`
- I can see you’re starting to use the return keyword to exit early from functions. Just make sure you are consistent with it, for example you could have removed the `else if` here. Notice I also removed the var 😉

```jsx
const handleKeyPress = (event) => {
    if(!isGameStart){ 
        setTimeout(() => { 
            startGame(); 
        }, "1000");
        return;
    }

    const key = event.key;

    if (key == 'w' || key == ' ') {
        //move up
        playerJump(); 
        return; 
    }
     if (key == 'a') {
        //move left
        moveElement(player, -32);
        return; 
    }
        moveElement(player, 32);
};
```

**Comment by MustafaNasirov** [comment]
### Thank you for your feedback! :) 

I made the changes to my functions where I didn't exit early, and the few vars that I left out. 

Also fixed an annoying bug with the score where it didn't stop incrementing/sped up. I'll add some more styling or features later on.

**Comment by MustafaNasirov** [comment]
### Thank you for your feedback! :) 

I made the changes to my functions where I didn't exit early, and the few vars that I left out. 

Also fixed an annoying bug with the score where it didn't stop incrementing/sped up. I'll add some more styling or features later on.
